### ISSUE TITLE
Release at Maven Central ?

### ISSUE THREAD

**Issue by martin-g** [danekja/jdk-serializable-functional#1]
Hi,

Do you plan to release this library at Maven Central ?

**Comment by danekja** [comment]
Hello Martin,

I wasn't planning to as it seemed to be for my use only. If you wish to use it, I'm willing to go through the process though :).

**Comment by martin-g** [comment]
Hi Jakub!

We (Apache Wicket) will need it.
At the moment we have few of those classes created by ourselves (https://github.com/apache/wicket/tree/master/wicket-core/src/main/java/org/apache/wicket/lambda) but we foresee that in near future many projects will need serializable version of those classes and it will be better if there is a library like this one that provides them instead of everyone to roll its own ones.

The only requirement we have is the library to be ASL2 compatible, e.g. licenced either with MIT, ASL2, BSD, or any other that is compatible (I don't know them by heart). **Update**: I see that you use MIT licence, and this is perfect!

**Comment by danekja** [comment]
Well, in that case I will be happy to deploy the library to Maven Central. We have been using Wicket in some of our projects for quite some time. Happy to give something back :).

**update:** typo :)

**Comment by danekja** [comment]
Ok, the project should be ready for deployment to Central. I have requested my domain name space with Sonatype, so now waiting for them to get back to me for confirmation.

**Comment by danekja** [comment]
http://central.maven.org/maven2/org/danekja/jdk-serializable-functional/1.8.1/

Modified README with the information.

The library has been successfully deployed to Maven Central. Anything else I can do?

**Comment by martin-g** [comment]
Thanks!
We will migrate our code to use your library and we will let you know if we face any issues!
