### ISSUE TITLE
New release to maven central

### ISSUE THREAD

**Issue by papegaaij** [danekja/jdk-serializable-functional#4]
Hi,

We've migrated Wicket to the interfaces from your library and would like to use the new methods and interfaces. Also, at the company I work for (Topicus), we would like to deprecate our current serializable interfaces in favor of yours. Can you please release 1.8.2 to Maven central so we can use them via an official channel?

Best regards,
Emond

**Comment by danekja** [comment]
Hi,

ok, great! I'm going to do it tomorrow.

Best regards,
Jakub

**Comment by papegaaij** [comment]
Superb! Thanks for the quick response!

**Comment by danekja** [comment]
Done, sorry for the delay. Unexpected things influenced my schedule.

**Comment by papegaaij** [comment]
No problem. I still consider 3 days fairly quick. Thanks for your help!
