### ISSUE TITLE
Bundle-Symbolic name is messed up

### ISSUE THREAD

**Issue by laeubi** [danekja/jdk-serializable-functional#8]
The current version 1.8 on maven central has a symbolic name of "checkout" but should be something like
Bundle-Name: serializable-function
in the MANIFEST.MF

**Comment by danekja** [comment]
Weird, I'm gonna look into it today or tomorrow.

Thanks for reporting.

Dne 18. 12. 2017 12:06 PM napsal uživatel "Christoph Läubrich" <
notifications@github.com>:

**Comment by danekja** [comment]
Caused by combination of bnd configuration errors on my side. Fixed and released to maven central as 1.8.5, should be available at some point today.
